---
title: "tarefa 1"
author: "Diego dos Santos Fernandes"
date: "22/10/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(stargazer)
library(kableExtra)
library(janitor)


library(readr)
battles <- read_csv("battles.csv")

library(readr)
deaths <- read_csv("character-deaths.csv")


```


```{r}

#Tabela 1

tabela1 <- battles %>%
  group_by(attacker_king) %>%
  summarise(name = n()) %>% 
  mutate(rel.freq = paste0(round(100 * name/sum(name), 0), "%"),
         attacker_king = replace_na(attacker_king, "Não Informado"))



  
tabela1 <- tabela1 %>%
  rename(`Rei Agressor` = attacker_king,
         `Qtd batalhas` = name,
         `Frequencia` = rel.freq) %>% 
  kable() %>%
  kable_styling(bootstrap_options = "striped") %>% 
  footnote(general = "Duas Batalhas não a variável Rei Agressor Informado")


tabela2.0 <-  battles %>%
   group_by(attacker_king, attacker_outcome) %>% 
  summarise(name = n()) %>% 
  na.omit()
 
tabela2.1 <- tabela2.0 %>%  
  spread(key = attacker_outcome, value = name)

tabela2.1 <- tabela2.1 %>% 
  mutate(loss = replace_na(loss,0)) %>% 
  mutate(tx_sucesso =  paste0 (round( 100 * win/(win + loss),2), "%"))
  

tabela2 <- tabela2.1

tabela2 <- tabela2 %>% 
  rename(`Rei Agressor` = attacker_king,
         `Derrotas` = loss,
         `Vitórias` = win) %>% 
  kable() %>%
    kable_styling(bootstrap_options = "striped") %>% 
    footnote(general = "Retirou-se duas batalhas que não continha o Rei Agressor")




```

## tabelas Finais

Depois da limpeza dos dados, separamos as duas tabelas formatadas

```{r}

tabela1
tabela2

```


# Segunda Bade de dados

```{r}
deaths_T1 <- deaths %>% 
  select(Name, Allegiances, Nobility) %>%
  mutate(Nobility = recode(Nobility,
                                    "1" = "Nobre",  
                                    "0" = "Pebleu")) %>% 
  group_by(Allegiances, Nobility) %>%
  summarise(n_mortos= n()) %>%
  spread(Nobility,n_mortos) %>% 
   kable() %>%
    kable_styling(bootstrap_options = "striped") %>% 
    footnote(general = "253 mortos não estão associado a nehuma classe")


deaths_T1


```























