---
title: "Exercicios em aula"
author: "Diego dos Santos Fernandes"
date: "26/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readr)
library(stargazer)
library(kableExtra)
library(ggplot2)
library(ggthemes)

```

#Exercício em sala

```{r}
# dados da Rais do Acre
df <- read.csv("micro_dados_salario.csv")


```

```{r}
# retirando dados faltantes e linhas iguais

df <- df %>%  select(-X)

df <- df %>% filter(rem_med_r > 0) %>%  na.omit() %>% distinct()

```



```{r}
# tranformando categorias na Rais

df <- df %>% mutate(genero = recode_factor(genero, `1` = "Homem", `2` = "Mulher"),
                                           raca_cor = recode_factor(raca_cor, `1` = "Indígena", `2` = "Branca", `4` = "Preta",`6` = "Amarela", `8` = "Parda"), 
                                           grau_instr = recode_factor(grau_instr,
`1` = "Até fundamental completo", `2` = "Até fundamental completo",
`3` = "Até fundamental completo", `4` = "Até fundamental completo",
`5` = "Até fundamental completo", `6` = "Até médio completo", `7` = "Até médio completo",
`8` = "Até médio completo", `9` = "Superior completo", `10` = "Superior completo",
`11` = "Superior completo", ))

```
 

```{r}
# retirando a população Indígena

df<- df %>% filter(raca_cor!="Indígena")
## converter para salário diario
df<- df %>% mutate(wage= rem_med_r/30) %>%
filter(rem_med_r>500 & rem_med_r <10000)
#### Usar group_by para analisar os dados
df %>% group_by(grau_instr) %>%
summarise (n= n(), wage_medio= mean(wage)) %>% 
  kable( format = "markdown") 
   



```

```{r}
#grafico 1

ggplot(df, aes( x = raca_cor, fill = genero))+
  geom_bar()+
  theme_minimal()+
  labs(
    x = "Raça/Cor", 
    title = "Distribuição de gênero e raça na amostra",
    subtitle = "Gênero",
    y = "Contagem"
  )


```



```{r}
#Grafico 2

ggplot(df, aes( x = raca_cor, fill = grau_instr))+
  geom_bar()+
  theme_minimal()+
  labs(
    x = "Raça/Cor", 
    title = "Distribuição de gênero e raça na amostra",
    subtitle = "Grau de instrução",
    y = "Contagem"
  )

```

```{r}
ba <- read_csv("BrasilArgentinaFutebol.csv")
 
ba <-  ba %>%  mutate( GolAcumBRA = cumsum(Brasil))
ba <-  ba %>%  mutate( GolAcumARG = cumsum(Argentina))
ba<- ba %>% mutate(vt_br= if_else( Brasil == Argentina, "Empate", if_else(Brasil > Argentina, "Vitória","Derrota")))
ba <- ba %>% mutate(saldo_pj = Argentina - Brasil)

```


```{r}

# gráficos da tabela em aula

# Gráfico 1

g1 <- ba %>% 
  filter(tournament  %in% c("FIFA World Cup qualification", "Copa América", "Friendly", "FIFA World Cup" )) %>% 
  group_by(tournament, vt_br) %>% 
  summarise(qts = n())


g1 %>% 
  ggplot(aes(x = reorder(tournament,qts), y = qts, fill = vt_br))+
  geom_bar(stat="identity", position = "dodge2")+
  scale_y_continuous(breaks = seq (0,15,1))+
    labs(
    title = "Resultado dos jogos por torneio",
    y = "Quantidade de jogos por torneio",
    x = "Torneio",
    caption = " Alguns campeonatos foram retirados para melhorar a visualização do Gráfico") +   theme_clean()

 
  



```


```{r}

# Gráfico 2
  
ba %>% 
  ggplot(aes(x = year))+
  geom_line( aes( y = GolAcumARG), color = "darkred")+
  geom_line(aes(y = GolAcumBRA), color = "steelblue", linetype="twodash")+
  labs(
  title = "Saldo Acumulado ao Longo dos anos",
    y = "Quantidade de gols acumulados",
    x = "Ano")+
  theme_tufte()


```










